name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: |
          cd client && npm ci
          cd ../server && npm ci

      - name: ✅ Lint/Build Client
        run: |
          cd client
          npm run build

      - name: ✅ Lint Backend
        run: |
          cd server
          npm run lint || true
